name: Bug report
description: Create a report to help us improve
labels: [bug]
title: "[bug] "
body:
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: List the exact steps to reproduce the behavior.
      placeholder: |
        1. Go to ...
        2. Click on ...
        3. See error
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
  - type: textarea
    id: logs
    attributes:
      label: Logs / Screenshots
      description: If applicable, add logs or screenshots to help explain your problem.
  - type: input
    id: version
    attributes:
      label: Plugin version
      placeholder: e.g., v1.0.0
  - type: textarea
    id: env
    attributes:
      label: Environment
      description: OS, Joplin version, any other context
