name: Feature request
description: Suggest an idea for this project
labels: [enhancement]
title: "[feat] "
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: Is your feature request related to a problem? Please describe.
  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: Describe the solution you'd like and how it improves the plugin.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
  - type: textarea
    id: context
    attributes:
      label: Additional context / screenshots
